name: falcon_2
description: Falcon

publish_to: 'none'

version: 3.0.0+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  bitsdojo_window: ^0.1.1+1
  shared_preferences: ^2.0.13
  flutter_riverpod: ^1.0.3
  objectbox_flutter_libs: ^1.3.0
  objectbox: ^1.3.0
  flutter_svg: ^1.0.3
  http: ^0.13.4
  dio: ^4.0.4
  path_provider: ^2.0.9
  internet_connection_checker: ^0.0.1+3
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  syncfusion_flutter_charts: ^19.4.53
  cached_network_image: ^3.2.0
  lottie: ^1.2.2
  currency_text_input_formatter: ^2.1.5
  webview_windows: ^0.1.6
  enough_mail: ^1.3.6
  html: ^0.15.0
  async: ^2.8.2
  file_picker: ^4.4.0
  url_launcher: ^6.0.20
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  objectbox_generator: ^1.3.0
  build_runner: ^2.1.7
  msix: ^3.2.0


flutter:
  uses-material-design: true
  assets:
    - assets/svg1/
    - assets/svg2/
    - assets/svg3/
    - assets/svg4/
    - assets/png/
    - assets/svg_drawer/
    - assets/my_lotties/

  fonts:
    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: InterExtraBold
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf

msix_config:
  display_name: Falcon
  publisher_display_name: Falcon LLC
  identity_name: AnorGroup.desktop.Falcon
  msix_version: 3.0.0.2
  dont_install_cert: true