name: falcon_2
description: Falcon

publish_to: 'none'

version: 4.0.1+0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  shared_preferences: ^2.0.13
  flutter_riverpod: ^2.0.0-dev.9
  objectbox_flutter_libs: ^1.4.1
  objectbox: ^1.4.1
  flutter_svg: ^1.0.3
  http: ^0.13.4
  dio: ^4.0.4
  path_provider: ^2.0.9
  internet_connection_checker: ^0.0.1+4
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.2.48
  cached_network_image: ^3.2.1
  lottie: ^1.4.2
  currency_text_input_formatter: ^2.1.7
  webview_windows: ^0.2.1
  enough_mail: ^2.1.1
  html: ^0.15.0
  async: ^2.8.2
  file_picker: ^5.0.1
  url_launcher: ^6.0.20
  latlong2: ^0.8.1
  connectivity_plus: ^2.3.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  objectbox_generator: ^1.4.1
  build_runner: ^2.1.10


flutter:
  uses-material-design: true
  assets:
    - assets/svg1/
    - assets/svg2/
    - assets/svg3/
    - assets/svg4/
    - assets/png/
    - assets/svg_drawer/
    - assets/my_lotties/

  fonts:
    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: InterExtraBold
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf

